# Generated by Django 4.0.5 on 2022-06-27 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supertype',
            old_name='type',
            new_name='super_type',
        ),
    ]
